Add test for unobserved schemes
The script is attempting to ensure backwards compatibility while but it could easily
break with new changes to pubMLST.

Adding this support will notify the user of any unobserved schemes that were expected.

Changes can then be caught.

Requires a file with a list of expected schemes to be in the same folder
as the script.

diff --git a/scripts/mlst-download_pub_mlst b/scripts/mlst-download_pub_mlst
--- a/scripts/mlst-download_pub_mlst
+++ b/scripts/mlst-download_pub_mlst
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-# TODO:
-# FIX oralstrep --- deconvolute multiple schemes
-# FIX leptospira loci names (extra _\d suffix)
-# FIX streptothermophilus AND sthermophilus
-
 set -e
+
+# GET SCRIPT DIRECTORY
+# need this to read the current supported schemes list
+# and test if all were found in the end
+
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+SCHEME_LIST=${SCRIPT_DIR}/schemes_list.txt
+echo "# $SCHEME_LIST"
+OBSERVED_SCHEMES=() # EMPTY ARRAY TO STORE THE OBSERVED SCHEMES
 
 ## SCHEMES TO BE IGNORED BECAUSE THEY ARE FUNGII OR PARASITE
 IGNORED_SCHEMES=("afumigatus" "blastocystis" "calbicans" "cglabrata" "ckrusei" "ctropicalis" "csinensis" "geotrichum" "kseptempunctata" "sparasitica" "tvaginalis")
@@ -218,6 +222,7 @@ for URL in $(grep '<url>' $OUTDIR/dbases.xml | sed -E 's/<\/?url>//g'); do
       continue
     # whatever you want to do when IGNORED_SCHEMES contains value
     fi  
+    OBSERVED_SCHEMES+=( $PROFILE )
     PROFILEDIR="$OUTDIR/$PROFILE"
     echo "mkdir -p '$PROFILEDIR'"
     echo "(cd '$PROFILEDIR' && echo "$URL" && wget -q '$URL' -O '$PROFILE.txt')"
@@ -234,3 +239,41 @@ done
 # echo rm -frv "$OUTDIR"/{afumigatus,blastocystis,calbicans,cglabrata,ckrusei}
 # echo rm -frv "$OUTDIR"/{ctropicalis,csinensis,geotrichum,kseptempunctata,sparasitica,tvaginalis}
 
+
+>&2 echo "# CHECKING FOR UNOBSERVED SCHEMES..."
+# implementing some sort of double check to ensure we are not missing anything
+# and warn the user of possible missing schemes
+
+printf "%s\n" "${OBSERVED_SCHEMES[@]}" > ${TMPDIR}/obs_schemes.txt
+UNOBSERVED_SCHEMES=$(comm -13 <(sort ${TMPDIR}/obs_schemes.txt) <(sort ${SCHEME_LIST}))
+
+# exit early if nothing else to do
+if [[ "x$UNOBSERVED_SCHEMES" == "x" ]];
+then
+  >&2 echo "# ALL EXPECTED SCHEMES WERE OBSERVED... SUCCESS!"
+  exit 0
+fi
+
+# list of schemes that have been deprecated for one reason or another
+# yersinia --- Pasteur has deprecated the Yersnia MLST scheme. It now only
+#              supports the cgMLST scheme (checked 05/April/2021)
+DEPRECATED_SCHEMES=('yersinia')
+
+# clean up
+rm -f ${TMPDIR}/obs_schemes.txt
+
+# create some colour
+YELLOW="\e[33m"
+ENDCOLOR="\e[0m"
+
+# print out missing schemes
+for scheme in ${UNOBSERVED_SCHEMES};
+do
+  if [[ " ${DEPRECATED_SCHEMES[@]} " =~ " ${scheme} " ]]; then
+      >&2 echo "# ${scheme} WAS NOT OBSERVED BUT IT IS DEPRECATED."
+      continue
+  fi  
+  >2& echo -e "${YELLOW}# WARNING: DID NOT OBSERVED THE SCHEME ${scheme}${ENDCOLOR}"
+done
+
+>&2 echo "# DONE."
